{
 "title": "Total Oxygen Level",
 "tags": [
  "object",
  "measurements"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "(%)" } },
   "targets": [
    { "expression": "$E+$F+$G+$H", "type": "math" }
   ]
  },
  {
   "title": "TS1 North Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "(%)" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MEA_DATE AS \"time\",\n  MEA_VALUE1\nFROM gam_measurement\nWHERE\n  $__timeFilter(MEA_DATE) AND\n  MEA_OBJECT_ID = 178\nORDER BY MEA_DATE"
    }
   ]
  },
  {
   "title": "TS1 South Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "(%)" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MEA_DATE AS \"time\",\n  MEA_VALUE1\nFROM gam_measurement\nWHERE\n  $__timeFilter(MEA_DATE) AND\n  MEA_OBJECT_ID = 179\nORDER BY MEA_DATE"
    }
   ]
  },
  {
   "title": "TS2 East Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "(%)" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MEA_DATE AS \"time\",\n  MEA_VALUE1\nFROM gam_measurement\nWHERE\n  $__timeFilter(MEA_DATE) AND\n  MEA_OBJECT_ID = 180\nORDER BY MEA_DATE"
    }
   ]
  },
  {
   "title": "TS2 West Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "(%)" } },
   "targets": [
    {
     "rawSql": "SELECT\n  MEA_DATE AS \"time\",\n  MEA_VALUE1\nFROM gam_measurement\nWHERE\n  $__timeFilter(MEA_DATE) AND\n  MEA_OBJECT_ID = 181\nORDER BY MEA_DATE"
    }
   ]
  }
 ]
}